name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker build . -f Dockerfile -t docker.pkg.github.com/BhanuTabeti/Smartgrid_API:latest
        docker login 
        docker push docker.pkg.github.com/BhanuTabeti/Smartgrid_API:latest
